spring.application.name=ajax

# Conexión a la base de datos MySQL en Aiven (Apuntando a la BD 'mascotas')
spring.datasource.url=jdbc:mysql://mascotas-navarrovegajosedavid-9db9.l.aivencloud.com:26446/mascotas?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS__IVrVEh84-KGQ8A34yh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true